name: CI Pipeline & Docker Build (Advanced)

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          pip install mlflow==2.19.0 pandas scikit-learn dagshub matplotlib

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Train, Build and Push Docker
        run: |
          # 1. Cari folder project
          MLPROJECT_FILE=$(find . -type f -iname "MLproject" | head -n 1)
          TARGET_DIR=$(dirname "$MLPROJECT_FILE")
          
          # 2. Jalankan Training
          mlflow run "$TARGET_DIR" --env-manager local
          
          # 3. AMBIL RUN ID YANG REAL (Bukan folder 'datasets')
          # Kita cari folder yang namanya panjang (hex) dan paling baru di mlruns/0
          RUN_ID=$(ls -dt mlruns/0/*/ | xargs -n 1 basename | grep -E '^[0-9a-f]{32}$' | head -n 1)
          
          echo "Beneran dapet Run ID: $RUN_ID"
          
          # 4. Build Docker Image
          mlflow models build-docker \
            -m "mlruns/0/$RUN_ID/artifacts/model" \
            -n "${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest" \
            --enable-mlserver

          # 5. Push ke Docker Hub
          docker push "${{ secrets.DOCKER_USERNAME }}/heart-disease-model:latest"