name: CI Pipeline & Docker Build (Advanced)

on: [push]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: pip install mlflow==2.19.0 pandas scikit-learn dagshub matplotlib

      - name: Train Model with MLflow Project
        run: |
          TARGET_DIR=$(find . -iname "MLproject" -exec dirname {} \; | head -n 1)
          cd "$TARGET_DIR"
          # Tambahin --env-manager local biar gak error Conda lagi
          mlflow run . --env-manager local

      - name: Populate .workflow folder
        run: |
          # Pastikan folder tujuan ada
          mkdir -p Workflow-CI/.workflow
          cp .github/workflows/ci_pipeline.yml Workflow-CI/.workflow/ci_pipeline.yml || true

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          TARGET_DIR=$(find . -name "modelling.py" -exec dirname {} \; | head -n 1)
          cd "$TARGET_DIR"
          
          RUN_ID=$(cat last_run_id.txt)
          echo "Building Docker Image for Run ID: $RUN_ID"
          
          mlflow models build-docker \
            -m "runs:/$RUN_ID/model" \
            -n "alvinmahesa/heart-disease-model:latest" \
            --enable-mlserver
          
          docker push "alvinmahesa/heart-disease-model:latest"